### ISSUE TITLE
テンプレートをクリックした時に前のテンプレートのレイアウトが引き継がれる

### ISSUE THREAD

**Issue by fumisoro** [fumisoro/C3S2#3]
テンプレートを押されたら必ず
文字色
背景色
リンク
フォント
フォントサイズ
太字の有無
を設定するようにする

**Comment by fumisoro** [comment]
b-type17 青地に白

<p>&<h>　navy　（文字色）
<background>　white　（背景色）
<link>　fuchsia　一度入ったページ　red　（リンク）
<font-family> 'ヒラギノ角ゴ Pro W3’ ‘メイリオ’　（フォント）
＊<h>タグのみ<bold>　（太字の有無）

文字サイズの指定がないからいいのかな？

**Comment by s-takumi** [comment]
試したサイトのURL載せてくれる？

**Comment by fumisoro** [comment]
@s-takumi  b17押すと、文字色と背景色だけ変化して文字サイズは前のテンプレートのサイズが引き継がれてるんだけど、あかんくない？
例えば、
b11、b17の順で押すと、b11で文字サイズ大きくなって、b17で文字色は変わるけど文字サイズはそのままになってる。

**Comment by s-takumi** [comment]
b17だけフォントサイズの指定が抜けてたみたい

**Comment by fumisoro** [comment]
結構抜けてるやつあるね
文字色
背景色
リンク
フォント
フォントサイズ
太字の有無
の項目は毎回再設定しないとだね。
